[versions]
# Kotlin and Android
iconsLucide = "1.0.0"
kotlin = "2.2.0"
android-gradle = "8.6.1"
ksp = "2.2.0-2.0.2"


compose-ui-version = "1.8.3"
compose-activity = "1.10.1"

# Ktor
ktor = "3.1.3"

# Accompanist
accompanist = "0.32.0"
accompanist-systemui = "0.32.0"
accompanist-pager = "0.32.0"
coil = "3.2.0"

# Material3
material3 = "1.3.2"

# Koin
koin = "4.0.0"
koin-core = "4.1.0"

# Kotlinx
kotlinx-serialization = "1.9.0"
kotlinx-datetime = "0.6.2"
kotlinx-coroutines = "1.10.2"

# Moko
moko-mvvm = "0.16.1"

# Splash Screen
splash-screen = "1.0.1"

# SDK Versions
compileSdk = "35"
minSdk = "23"
targetSdk = "35"

room = "2.7.0"
sqlite = "2.4.0"

[libraries]
# Kotlin and Android
icons-lucide = { module = "com.composables:icons-lucide", version.ref = "iconsLucide" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui-version" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui-version" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose-ui-version" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-ui-version" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }

# Material3
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material3-window = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

# Accompanist
accompanist-coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
accompanist-systemui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemui" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-pager" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist-pager" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }

# Koin
koin-android = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-core" }

# Kotlinx
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# Moko
moko-mvvm-core = { module = "dev.icerock.moko:mvvm-core", version.ref = "moko-mvvm" }

# Splash Screen
splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "splash-screen" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

# Test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[bundles]
ktor-common = [
    "ktor-client-core",
    "ktor-client-json",
    "ktor-client-logging",
    "ktor-client-serialization",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json"
]

compose = [
    "compose-ui",
    "compose-ui-tooling",
    "compose-ui-util",
    "compose-activity"
]

accompanist = [
    "accompanist-coil",
    "accompanist-webview"
]

material3 = [
    "material3",
    "material3-window"
]

kotlinx = [
    "kotlinx-serialization-core",
    "kotlinx-datetime"
]

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" } 